[package]
name = "mi4ulings"
version = "0.1.0"
edition = "2024"
resolver="3"

[workspace]
members = ["crates/docling"]

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full", "tracing"] }

