[package]
name = "mi4ulings-config"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1"